"""add control plan tables

Revision ID: 258fff829a6f
Revises: 72eca8bb991f
Create Date: 2026-04-29 15:02:51.383073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '258fff829a6f'
down_revision = '72eca8bb991f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('control_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('cp_no', sa.String(length=50), nullable=False),
    sa.Column('revision', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('process_type', sa.String(length=50), nullable=True),
    sa.Column('audit_date', sa.Date(), nullable=True),
    sa.Column('auditor', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('supplier_id', 'part_id', name='uq_cp_supplier_part')
    )
    with op.batch_alter_table('control_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_control_plans_cp_no'), ['cp_no'], unique=True)
        batch_op.create_index(batch_op.f('ix_control_plans_part_id'), ['part_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_control_plans_process_type'), ['process_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_control_plans_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_control_plans_supplier_id'), ['supplier_id'], unique=False)

    op.create_table('process_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cp_id', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('process_name', sa.String(length=100), nullable=False),
    sa.Column('process_code', sa.String(length=50), nullable=True),
    sa.Column('machine', sa.String(length=100), nullable=True),
    sa.Column('is_key_process', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['cp_id'], ['control_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('process_steps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_process_steps_cp_id'), ['cp_id'], unique=False)

    op.create_table('control_characteristics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('step_id', sa.Integer(), nullable=False),
    sa.Column('char_name', sa.String(length=150), nullable=False),
    sa.Column('spec_value', sa.String(length=100), nullable=True),
    sa.Column('spec_unit', sa.String(length=30), nullable=True),
    sa.Column('tolerance', sa.String(length=50), nullable=True),
    sa.Column('control_method', sa.String(length=150), nullable=True),
    sa.Column('sample_size', sa.String(length=50), nullable=True),
    sa.Column('frequency', sa.String(length=50), nullable=True),
    sa.Column('reaction_plan', sa.Text(), nullable=True),
    sa.Column('is_key_char', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['step_id'], ['process_steps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('control_characteristics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_control_characteristics_step_id'), ['step_id'], unique=False)

    with op.batch_alter_table('edc_reports', schema=None) as batch_op:
        batch_op.alter_column('classification',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('report_date',
               existing_type=sa.DATE(),
               nullable=True)

    with op.batch_alter_table('parts', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_parts_pn'), ['pn'], unique=False)
        batch_op.create_unique_constraint('uq_supplier_part_number', ['supplier_id', 'pn'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parts', schema=None) as batch_op:
        batch_op.drop_constraint('uq_supplier_part_number', type_='unique')
        batch_op.drop_index(batch_op.f('ix_parts_pn'))
        batch_op.alter_column('description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)

    with op.batch_alter_table('edc_reports', schema=None) as batch_op:
        batch_op.alter_column('report_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('classification',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    with op.batch_alter_table('control_characteristics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_control_characteristics_step_id'))

    op.drop_table('control_characteristics')
    with op.batch_alter_table('process_steps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_process_steps_cp_id'))

    op.drop_table('process_steps')
    with op.batch_alter_table('control_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_control_plans_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_control_plans_status'))
        batch_op.drop_index(batch_op.f('ix_control_plans_process_type'))
        batch_op.drop_index(batch_op.f('ix_control_plans_part_id'))
        batch_op.drop_index(batch_op.f('ix_control_plans_cp_no'))

    op.drop_table('control_plans')
    # ### end Alembic commands ###
