"""Add business trip tables

Revision ID: 72eca8bb991f
Revises: 
Create Date: 2026-01-26 14:07:37.552575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72eca8bb991f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_trips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_no', sa.String(length=50), nullable=False),
    sa.Column('engineer', sa.String(length=100), nullable=False),
    sa.Column('supplier_code', sa.String(length=50), nullable=True),
    sa.Column('supplier_name', sa.String(length=200), nullable=False),
    sa.Column('supplier_location', sa.String(length=200), nullable=True),
    sa.Column('purpose', sa.Text(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('days', sa.Integer(), nullable=True),
    sa.Column('audit_type', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('estimated_cost', sa.Float(), nullable=True),
    sa.Column('actual_cost', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('business_trips', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_business_trips_start_date'), ['start_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_business_trips_supplier_code'), ['supplier_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_business_trips_supplier_name'), ['supplier_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_business_trips_trip_no'), ['trip_no'], unique=True)

    op.create_table('trip_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('doc_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('stored_name', sa.String(length=255), nullable=False),
    sa.Column('rel_path', sa.String(length=500), nullable=False),
    sa.Column('mime', sa.String(length=100), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['trip_id'], ['business_trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trip_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trip_documents_trip_id'), ['trip_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trip_documents_trip_id'))

    op.drop_table('trip_documents')
    with op.batch_alter_table('business_trips', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_business_trips_trip_no'))
        batch_op.drop_index(batch_op.f('ix_business_trips_supplier_name'))
        batch_op.drop_index(batch_op.f('ix_business_trips_supplier_code'))
        batch_op.drop_index(batch_op.f('ix_business_trips_start_date'))

    op.drop_table('business_trips')
    # ### end Alembic commands ###
